(() => {
  const data = window.HQ_DATA;
  const root = document.getElementById('content');
  const nav = document.getElementById('sidebar-nav');
  const title = document.getElementById('view-title');
  const subtitle = document.getElementById('view-subtitle');
  const eyebrow = document.getElementById('view-eyebrow');
  const drawer = document.getElementById('drawer');
  const drawerContent = document.getElementById('drawer-content');

  document.getElementById('today-label').textContent = new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',weekday:'short'}).format(new Date());
  const statusClass=s=>({working:'green',reviewing:'yellow',waiting:'',completed:'green',COMPLETED:'green','IN PROGRESS':'yellow',REVIEW:'blue',WAITING:'',REQUIRED:'red',DECIDED:'green',RUNNING:'blue',PLANNED:''})[s]||'';
  const pct=n=>Math.max(0,Math.min(100,Number(n)||0));
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));

  const sections=[
    {title:'Company',items:[{id:'company',label:'Company Overview',icon:'🏠'},{id:'commands',label:'CEO Commands',icon:'⭐'}]},
    {title:'Organization',items:[
      {id:'team:coo',label:'COO',icon:'🤖',status:'reviewing'},
      {id:'team:discovery',label:'Discovery',icon:'🔬',status:'reviewing',children:[{id:'agent:market',label:'Market Research'},{id:'agent:competitor',label:'Competitor Intelligence'},{id:'agent:user-research',label:'User & Review Research'}]},
      {id:'team:product',label:'Product',icon:'🧠',status:'reviewing',children:[{id:'agent:pm',label:'Product Manager'},{id:'agent:ux',label:'UX'},{id:'agent:red-team',label:'Red Team'}]},
      {id:'team:engineering',label:'Engineering',icon:'💻',status:'waiting',children:[{id:'agent:tech-lead',label:'Tech Lead'},{id:'agent:developer',label:'Developer'},{id:'agent:qa',label:'QA'}]},
      {id:'team:growth',label:'Growth',icon:'🚀',status:'waiting',children:[{id:'agent:growth-lead',label:'Growth Lead'},{id:'agent:aso',label:'ASO'},{id:'agent:content',label:'Content Marketing'}]},
      {id:'team:data',label:'Data',icon:'📊',status:'waiting'},{id:'team:revenue',label:'Revenue',icon:'💰',status:'waiting'}]},
    {title:'Apps',items:data.apps.map(a=>({id:'app:'+a.id,label:a.name,icon:'📱',status:a.status}))},
    {title:'Work',items:[{id:'today',label:'Today',icon:'🕒'},{id:'tasks',label:'Tasks',icon:'📋'},{id:'experiments',label:'Experiments',icon:'🧪'},{id:'decisions',label:'Decisions',icon:'✅'},{id:'artifacts',label:'Artifacts',icon:'📄'}]}
  ];

  function renderNav(){nav.innerHTML=sections.map(s=>`<section><div class="nav-section-title">${s.title}</div><div class="nav-list">${s.items.map(item=>`<div><button type="button" class="nav-item" data-view="${item.id}"><span class="nav-icon">${item.icon||'•'}</span><span>${item.label}</span>${item.status?`<span class="nav-status ${item.status}"></span>`:''}</button>${item.children?`<div class="nav-children">${item.children.map(c=>`<button type="button" class="nav-item child" data-view="${c.id}">↳ ${c.label}</button>`).join('')}</div>`:''}</div>`).join('')}</div></section>`).join('');nav.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.view)))}
  function setHeader(k,h,s){eyebrow.textContent=k;title.textContent=h;subtitle.textContent=s}
  function activate(v){nav.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v))}
  function metric(l,v){return `<div class="metric"><span>${l}</span><strong>${v}</strong></div>`}
  function badge(t,c=''){return `<span class="badge ${c}">${t}</span>`}
  function timelineItem(a){return `<div class="timeline-item"><div class="timeline-time">${a.time}</div><div class="timeline-line"><span class="timeline-dot"></span></div><div class="timeline-content"><strong>${a.team} · ${a.title}</strong><p>${a.summary}</p></div></div>`}

  function companyView(){setHeader('COMPANY','Company Overview','목데이터 없이 실제 기록된 AI APP STUDIO 운영 현황');root.innerHTML=`
    <section class="hero"><div class="hero-grid"><div><span class="kicker">AI APP STUDIO</span><h2>제품을 만들고, 검증하고, 성장시키는 작은 AI 조직</h2><p>현재 대시보드는 실제로 확인·수행한 업무만 표시합니다. 미확인 수치와 가상 업무는 표시하지 않습니다.</p><div class="mission"><strong>Mission</strong><br>${data.company.mission}</div></div><div class="metric-grid">${metric('등록 앱 / 운영대상',data.company.apps)}${metric('참여 Teams',data.company.activeTeams)}${metric('진행 Task',data.company.activeTasks)}${metric('오늘 완료',data.company.completedToday)}${metric('실행 중 실험',data.company.experiments)}${metric('확정 Decision',data.company.ceoDecisions)}</div></div></section>
    <section class="section"><div class="section-head"><h2>App Portfolio</h2><span class="section-note">현재 실제 정보가 등록된 앱만 표시</span></div><div class="grid-3">${data.apps.map(app=>`<article class="card clickable" data-open-app="${app.id}"><div class="card-title"><h3>${app.name}</h3>${badge(app.stage,'blue')}</div><p class="section-note">${app.goal}</p><div class="mini-stats"><div class="mini-stat"><span>오늘 완료</span><strong>${app.today}</strong></div><div class="mini-stat"><span>진행</span><strong>${app.active}</strong></div><div class="mini-stat"><span>확정 결정</span><strong>${app.decisions}</strong></div></div><p class="section-note">최근 업데이트 ${app.updated}</p></article>`).join('')}</div></section>
    <div class="split"><section class="card"><div class="card-title"><h3>Today Summary</h3>${badge('DAILY CLOSE','green')}</div><p class="big-summary">${data.company.todaySummary}</p><div class="timeline">${data.activities.map(timelineItem).join('')}</div></section><section class="card"><div class="card-title"><h3>CEO Inbox</h3>${badge(data.decisions.filter(d=>d.status==='REQUIRED').length+' OPEN','red')}</div><div class="list">${data.decisions.filter(d=>d.status==='REQUIRED').map(d=>`<div class="list-row clickable" data-decision="${d.id}"><div class="grow"><strong>${d.title}</strong><p>${d.app} · ${d.team}</p></div>${badge('DISCUSS','red')}</div>`).join('')||'<div class="empty">대기 중인 결정 없음</div>'}</div></section></div>
    <section class="section"><div class="section-head"><h2>What we learned today</h2><span class="section-note">FACT / ANALYSIS / HYPOTHESIS / RED TEAM</span></div><div class="fact-grid">${data.findings.map(f=>`<div class="fact"><span class="type">${f.type}</span><p>${f.text}</p></div>`).join('')}</div></section>`;bindContent()}

  function teamView(id){const t=data.teams.find(x=>x.id===id);if(!t)return;setHeader('ORGANIZATION',t.icon+' '+t.name,t.role);const acts=data.activities.filter(a=>a.team===t.name);const tsks=data.tasks.filter(x=>x.team===t.name);const arts=data.artifacts.filter(x=>x.team===t.name);const people=data.agents.filter(a=>a.team===t.name);root.innerHTML=`<section class="hero"><div class="hero-grid"><div><span class="kicker">TEAM POSITION</span><h2>${t.name}</h2><p>${t.role}</p><div class="mission"><strong>오늘 의견</strong><br>${t.summary}</div></div><div class="metric-grid">${metric('담당 AI',t.ai)}${metric('완료',t.done)}${metric('진행',t.doing)}${metric('대기',t.waiting)}</div></div></section>${people.length?`<section class="section"><div class="section-head"><h2>Employee Opinions</h2><span class="section-note">각 역할의 독립 의견</span></div><div class="grid-3">${people.map(a=>`<article class="card clickable" data-agent-open="${a.id}"><div class="card-title"><h3>${a.name}</h3>${badge(a.status,statusClass(a.status))}</div><p class="big-summary" style="font-size:13px">${a.opinion}</p></article>`).join('')}</div></section>`:''}<div class="grid-2"><section class="card"><div class="card-title"><h3>Today Activity</h3>${badge(acts.length+' EVENTS','blue')}</div><div class="timeline">${acts.length?acts.map(timelineItem).join(''):'<div class="empty">오늘 Activity 없음</div>'}</div></section><section class="card"><div class="card-title"><h3>Tasks</h3></div><div class="list">${tsks.length?tsks.map(taskRow).join(''):'<div class="empty">Task 없음</div>'}</div></section></div><section class="section"><div class="section-head"><h2>Artifacts</h2></div><div class="grid-3">${arts.length?arts.map(artifactCard).join(''):'<div class="empty">Artifact 없음</div>'}</div></section>`;bindContent()}

  function agentView(id){const a=data.agents.find(x=>x.id===id);if(!a)return;setHeader('AI ROLE',a.name,a.team+' · '+a.ai);const related=data.tasks.filter(t=>t.role===a.name);root.innerHTML=`<section class="hero"><div class="hero-grid"><div><span class="kicker">${a.team.toUpperCase()}</span><h2>${a.name}</h2><p>${a.mission}</p><div class="mission"><strong>오늘 업무</strong><br>${a.task}</div></div><div class="metric-grid">${metric('AI',a.ai)}${metric('담당 앱',a.app)}${metric('상태',a.status.toUpperCase())}</div></div></section><section class="card"><div class="card-title"><h3>Independent Opinion</h3>${badge('POSITION','blue')}</div><p class="big-summary">${a.opinion}</p></section><section class="card"><div class="card-title"><h3>Assigned Tasks</h3></div><div class="list">${related.length?related.map(taskRow).join(''):'<div class="empty">현재 연결 Task 없음</div>'}</div></section>`;bindContent()}

  function appView(id){const app=data.apps.find(x=>x.id===id);if(!app)return;setHeader('APP PORTFOLIO',app.name,app.stage+' · '+app.goal);const tsks=data.tasks.filter(t=>t.app===app.name),acts=data.activities.filter(a=>a.app===app.name),decs=data.decisions.filter(d=>d.app===app.name),arts=data.artifacts.filter(a=>a.app===app.name);root.innerHTML=`<section class="hero"><div class="hero-grid"><div><span class="kicker">${app.stage}</span><h2>${app.name}</h2><p>${app.description}</p><div class="mission"><strong>Current Goal</strong><br>${app.goal}</div></div><div class="metric-grid">${metric('오늘 완료',app.today)}${metric('진행 Task',app.active)}${metric('실행 실험',app.experiments)}${metric('확정 Decision',app.decisions)}</div></div></section><section class="section"><div class="section-head"><h2>Current Analysis</h2><span class="section-note">오늘 실제 조사·화면 분석 결과</span></div><div class="fact-grid">${data.findings.map(f=>`<div class="fact"><span class="type">${f.type}</span><p>${f.text}</p></div>`).join('')}</div></section><div class="grid-2"><section class="card"><div class="card-title"><h3>Completed Tasks</h3></div><div class="list">${tsks.map(taskRow).join('')}</div></section><section class="card"><div class="card-title"><h3>Open Decisions</h3></div><div class="list">${decs.map(decisionRow).join('')}</div></section></div><section class="section"><div class="section-head"><h2>Artifacts</h2><span class="section-note">Google Drive 실제 문서</span></div><div class="grid-3">${arts.map(artifactCard).join('')}</div></section><section class="card"><div class="card-title"><h3>Today Activity</h3></div><div class="timeline">${acts.map(timelineItem).join('')}</div></section>`;bindContent()}

  function taskRow(t){return `<div class="list-row clickable" data-task="${t.id}"><div class="grow"><span class="command-id">${t.id} · ${t.command}</span><strong style="display:block;margin-top:4px">${t.title}</strong><p>${t.app} · ${t.role} · ${t.updated}</p><div class="progress"><span style="width:${pct(t.progress)}%"></span></div></div>${badge(t.status,statusClass(t.status))}</div>`}
  function decisionRow(d){return `<div class="list-row clickable" data-decision="${d.id}"><div class="grow"><strong>${d.title}</strong><p>${d.team} · ${d.summary}</p></div>${badge(d.status,statusClass(d.status))}</div>`}
  function expRow(e){return `<div class="list-row"><div class="grow"><span class="command-id">${e.id}</span><strong>${e.title}</strong><p>KPI · ${e.kpi}</p></div>${badge(e.status,statusClass(e.status))}</div>`}
  function artifactCard(a){return `<article class="card"><div class="card-title"><h3>${a.title}</h3>${badge(a.type,'blue')}</div><p class="section-note">${a.app} · ${a.team} · ${a.date}</p><p class="big-summary" style="font-size:13px">${a.summary}</p>${a.url?`<a class="artifact-link" href="${esc(a.url)}" target="_blank" rel="noopener">문서 열기 ↗</a>`:''}</article>`}

  function commandsView(){setHeader('CEO','CEO Commands','실제로 내린 지시와 실행 결과');root.innerHTML=`<section class="section"><div class="grid-2">${data.commands.map(c=>`<article class="card clickable" data-command="${c.id}"><div class="card-title"><div><span class="command-id">${c.id}</span><h3>${c.title}</h3></div>${badge(c.status,statusClass(c.status))}</div><p class="big-summary" style="font-size:13px">${c.text}</p><p class="section-note">${c.app} · ${c.time} · ${c.teams.join(' → ')}</p><div class="progress"><span style="width:${pct(c.progress)}%"></span></div></article>`).join('')}</div></section>`;bindContent()}
  function todayView(){setHeader('WORK','Today','오늘 실제로 발생한 업무와 조사 결과');root.innerHTML=`<div class="grid-2"><section class="card"><div class="card-title"><h3>Today Timeline</h3>${badge(data.activities.length+' EVENTS','blue')}</div><div class="timeline">${data.activities.map(timelineItem).join('')}</div></section><section class="card"><div class="card-title"><h3>Today Summary</h3></div><p class="big-summary">${data.company.todaySummary}</p><div class="fact-grid">${data.findings.map(f=>`<div class="fact"><span class="type">${f.type}</span><p>${f.text}</p></div>`).join('')}</div></section></div>`}
  function tasksView(){setHeader('WORK','Tasks','실제로 수행한 업무');root.innerHTML=`<section class="card"><div class="table-wrap"><table><thead><tr><th>ID</th><th>업무</th><th>앱</th><th>조직</th><th>역할</th><th>Command</th><th>상태</th><th>진행률</th></tr></thead><tbody>${data.tasks.map(t=>`<tr class="clickable" data-task="${t.id}"><td>${t.id}</td><td>${t.title}</td><td>${t.app}</td><td>${t.team}</td><td>${t.role}</td><td>${t.command}</td><td>${badge(t.status,statusClass(t.status))}</td><td>${t.progress}%</td></tr>`).join('')}</tbody></table></div></section>`;bindContent()}
  function simpleListView(kind){const map={experiments:['EXPERIMENTS','Experiments','실제로 실행 또는 확정된 실험',data.experiments,expRow],decisions:['DECISIONS','Decisions','CEO와 추가 논의가 필요한 미결정 쟁점',data.decisions,decisionRow],artifacts:['ARTIFACTS','Artifacts','오늘 생성·갱신된 실제 문서',data.artifacts,artifactCard]};const[k,h,s,items,renderer]=map[kind];setHeader(k,h,s);root.innerHTML=items.length?(kind==='artifacts'?`<section class="grid-3">${items.map(renderer).join('')}</section>`:`<section class="card"><div class="list">${items.map(renderer).join('')}</div></section>`):'<div class="empty">실제 등록 데이터가 없습니다.</div>';bindContent()}

  function openCommand(id){const c=data.commands.find(x=>x.id===id);if(!c)return;const related=data.tasks.filter(t=>t.command===id),acts=data.activities.filter(a=>a.command===id);drawerContent.innerHTML=`<span class="kicker">CEO COMMAND · ${c.id}</span><h2>${c.title}</h2><p class="big-summary">${c.text}</p><div class="card"><div class="card-title"><h3>Progress</h3>${badge(c.status,statusClass(c.status))}</div><div class="progress"><span style="width:${pct(c.progress)}%"></span></div></div><h3>Execution</h3><div class="tree-flow">${related.map(t=>`<div class="flow-node ${t.status==='COMPLETED'?'done':'waiting'}"><strong>${t.team} · ${t.title}</strong><span>${t.id} · ${t.status}</span></div>`).join('')}</div><h3>Result</h3><div class="list">${c.result.map(r=>`<div class="list-row"><strong>${r}</strong></div>`).join('')}</div><h3>Activity</h3><div class="timeline">${acts.map(timelineItem).join('')}</div>`;openDrawer()}
  function openTask(id){const t=data.tasks.find(x=>x.id===id);if(!t)return;drawerContent.innerHTML=`<span class="kicker">TASK · ${t.id}</span><h2>${t.title}</h2><p class="big-summary">${t.app} · ${t.team} · ${t.role}</p><div class="card"><div class="card-title"><h3>Status</h3>${badge(t.status,statusClass(t.status))}</div><p>CEO Command: <strong>${t.command}</strong></p><p>업데이트: ${t.updated}</p></div>`;openDrawer()}
  function openDecision(id){const d=data.decisions.find(x=>x.id===id);if(!d)return;drawerContent.innerHTML=`<span class="kicker">OPEN DECISION · ${d.id}</span><h2>${d.title}</h2><p class="big-summary">${d.summary}</p><div class="card"><div class="card-title"><h3>${d.app}</h3>${badge(d.status,statusClass(d.status))}</div><p class="section-note">제안 조직 · ${d.team}</p><p>아직 CEO Decision으로 확정되지 않았습니다.</p></div>`;openDrawer()}
  function openDrawer(){drawer.classList.add('open');drawer.setAttribute('aria-hidden','false')}
  function closeDrawer(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true')}
  function bindContent(){root.querySelectorAll('[data-open-app]').forEach(x=>x.addEventListener('click',()=>openView('app:'+x.dataset.openApp)));root.querySelectorAll('[data-command]').forEach(x=>x.addEventListener('click',()=>openCommand(x.dataset.command)));root.querySelectorAll('[data-task]').forEach(x=>x.addEventListener('click',()=>openTask(x.dataset.task)));root.querySelectorAll('[data-decision]').forEach(x=>x.addEventListener('click',()=>openDecision(x.dataset.decision)));root.querySelectorAll('[data-agent-open]').forEach(x=>x.addEventListener('click',()=>openView('agent:'+x.dataset.agentOpen)))}
  function openView(view){activate(view);if(view==='company')companyView();else if(view==='commands')commandsView();else if(view==='today')todayView();else if(view==='tasks')tasksView();else if(['experiments','decisions','artifacts'].includes(view))simpleListView(view);else if(view.startsWith('team:'))teamView(view.split(':')[1]);else if(view.startsWith('agent:'))agentView(view.split(':')[1]);else if(view.startsWith('app:'))appView(view.split(':')[1]);window.scrollTo({top:0,behavior:'smooth'})}
  drawer.querySelectorAll('[data-close-drawer]').forEach(x=>x.addEventListener('click',closeDrawer));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});document.getElementById('refresh-btn').addEventListener('click',()=>openView(document.querySelector('.nav-item.active')?.dataset.view||'company'));
  renderNav();openView('company');
})();